### ISSUE TITLE
Adenoviroma

### ISSUE THREAD

**Issue by aguilpo** [qiime2/.github#13]
Análisis metagenómico de silaes de Agave salmiana

**Comment by lizgehret** [comment]
Hi @aguilpo,

Here's my understanding of your request:

_Metagenomic analysis of Agave salmiana silaes_

Without having any further details of your particular request, I'll direct you to our installation instructions for the [QIIME 2 Metagenomic Distribution](https://docs.qiime2.org/2024.5/install/native/#qiime-2-metagenome-distribution). This distribution contains analysis tools for shotgun metagenomic sequencing data. If you have any particular questions regarding the usage of these tools or run into any issues, please reach out on the [QIIME 2 Forum](https://forum.qiime2.org/). This is where you can discuss your current project and ask the community for help!

I'm going to close out this issue since this is not a bug report or feature request. Thanks!
